name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=muzammilsharf&show_icons=true&include_all_commits=true&theme=onedark
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top langs card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=muzammilsharf&layout=compact&theme=onedark
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 1
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=muzammilsharf&repo=RagPortfolioChatbot&theme=onedark
          path: profile/pin1.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card 2
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=muzammilsharf&repo=AI-Based-Morning-Briefing-Assistant&theme=onedark
          path: profile/pin2.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: stats-organization/github-readme-stats-action@v2
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          card: wakatime
          options: username=muzammilsharf&theme=onedark
          path: profile/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push